apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-user
  namespace: jhub
  labels:
    hub: jhub
    type: hubdb
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hub-user-storage
  local:
    path: /mnt/data/pv-user
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
          - node2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hub
  namespace: jhub
  labels:
    hub: jhub
    type: hubdb
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hub-storage
  local:
    path: /mnt/data/pv-hub
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node2
