apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-user
  namespace: jhub
spec:
  storageClassName: hub-user-storage
  resources:
    requests:
      storage: 2Gi
  accessModes:
  - ReadWriteOnce
  volumeName: "pv-user"
